[build]
  publish = "public" # El directorio que Netlify publicar치 como tu sitio est치tico
  functions = "netlify-functions" # El directorio donde buscar치 tus funciones de Lambda

[dev]
  command = "npm run start" # Comando para iniciar tu servidor local para desarrollo
  functions = "netlify-functions" # El directorio donde buscar치 tus funciones de Lambda para desarrollo local
